LDFLAGS=-L./

all: libstk.a
	make -C ./test

libstk.a: stk_log.o  stk_socket.o stk_pool.o stk_module.o stk_async_queue.o stk_threads.o daemon.o stk_signal.o
	ar cru $@ $>

%.o: %.c
	gcc -g -c $>

clean:
	rm -f *.o libstk.a
	cd test; make clean

.PHONY: all libstk.a clean
